site_name: "Ricky's Notes"
site_description: "Personal Technical Notes"
site_author: "Ricky Zaman"

# GitHub Pages configuration
site_url: https://riczaman.github.io/notes-repo/
repo_url: https://github.com/riczaman/notes-repo

theme:
  name: material
  font:
    text: Raleway
    code: Fira Code
  palette:
    primary: deep orange
    accent: green

  features:
     - content.code.copy
     - content.code.select
     - content.code.annotate


  
  # Static files
  static_templates:
    - 404.html


nav:
  - Home: index.md
  - Topics:
      - Jenkins: topics/jenkins.md
      - Docker: topics/docker.md
      - GitHub Actions: topics/actions.md
      - Oracle AI Foundations: topics/aiFoundations.md

# Ensure proper URL handling
strict: false

plugins:
  - search

# Static files configuration
docs_dir: docs
site_dir: site

# Exclude certain files from being processed as pages
exclude_docs: |
  topics/*.gif
  topics/*.png
  topics/*.jpg
  topics/*.jpeg

# GitHub Pages deployment
use_directory_urls: true

# Static assets configuration
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde