site_name: "Ricky's Notes"
site_description: "Personal Technical Notes"
site_author: "Ricky Zaman"

theme:
  name: material
  palette:
    primary: white
    accent: deep orange
  
  # Static files
  static_templates:
    - 404.html


nav:
  - Home: index.md
  - Topics:
      - Jenkins: topics/jenkins.md

plugins:
  - search

# Static files configuration
docs_dir: docs
site_dir: site

# Exclude certain files from being processed as pages
exclude_docs: |
  topics/*.gif
  topics/*.png
  topics/*.jpg
  topics/*.jpeg
