site_name: "Ricky's Notes"
site_description: "Personal Technical Notes"
site_author: "Ricky Zaman"

theme:
  name: material
  palette:
    primary: white
    accent: deep orange


nav:
  - Home: index.md
  - Topics:
      - Jenkins: topics/jenkins.md

plugins:
  - search

# Static files configuration
docs_dir: docs
site_dir: site
